mqtt:
    host: 10.0.0.210
    port: 1883
    client: kamstrup
    topic: kamstrup
serial_device:
    com_port: /dev/ttyUSB1
kamstrup:
    parameters:
    - energy
    - volume
    - temp1
    - temp2
    poll_interval: 28
